name: DailyRewards
version: '1.0-SNAPSHOT'
main: com.dailyrewards.DailyRewards
api-version: '1.21.4'
commands:
  daily:
    description: Gives you the daily rewards
    usage: /<command> <rank>
permissions:
  dailyreward.edit:
    description: Allows the player to edit the rewards.
    default: op
dependencies: [LuckPerms]